#! /bin/sh

dunst &
feh --bg-scale ~/Wallpapers/wallpaper_1.png
picom --experimental-backend -b

polybar &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 

bspc config border_width        1
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a google-chrome-stable desktop=8
